version: 0.2

phases:
  pre_build:
    commands:
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - REPO_URL=https://github.com/lallema/$IMAGE_REPO_NAME
      - pwd
      - ls -trl
      - hostname
